project:
  type: website
  output-dir: docs

website:
  title: "Kandace Loualhati"
  navbar:
    left:
      - text: "About Me"
      - href: index.qmd
      - text: "Data Viz"
        menu: 
          - text: "California Fire Damage"
            href: calfiredamage.qmd
          - text: "Employed Women"
            href: employedwomen.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    page-layout: full

editor: visual

