project:
  type: website
  output-dir: docs

website:
  title: "Kandace Loualhati"
  navbar:
    left:
      - href: index.qmd
      - text: "Data Science Projects"
        menu: 
          - text: "California Fire Damage"
            href: calfiredamage.qmd
          - text: "Employed Gender"
            href: employedwomen.qmd
          - text: "'The Office' Text Analysis"
            href: textanalysis.qmd
          - text: "Permutation Test"
            href: Permutationtest.qmd
          - text: "SQL"
            href: SQL_proj.qmd
          - text: "Web Scraping"
            href: WebScraping.qmd
          - text: "Presentation"
            href: DS02Presentation.qmd
      - text: "Political Papers"
        menu:
          - text: "Between a Prince and a Prostitute"
            href: Between-a-Prince-and-a-Prostitute.pdf
format:
  html:
    theme: minty
    css: styles.css
    toc: true
    page-layout: full

editor: visual

